services:
  taskly-api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DB_HOST: postgres_taskly_prod
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres_taskly_prod

  postgres_taskly_prod:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  postgres_taskly_test:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data


volumes:
  postgres_prod_data:
 
